USE h1_projekt;
/*CREATE TABLE opslag (
id INT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
opslag TEXT NOT NULL, 
created DATETIME DEFAULT CURRENT_TIMESTAMP,
modified DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);*/
#INSERT INTO opslag(opslag) VALUES ("dette er min status");
SELECT * FROM opslag;